# ---------- FRMK_ATTRIBUTE_TYPE ----------
select "Create FRMK_ATTRIBUTE_TYPE";
CREATE TABLE  FRMK_ATTRIBUTE_TYPE (
	ID varchar(36) NOT NULL,
	TIPO varchar(50) NOT NULL,
	TIPO_DESCRIZIONE varchar(500) NOT NULL,
	MULTILINGUAYN TINYINT(1) DEFAULT '0',
	LINGUADEFAULT varchar(50) DEFAULT NULL,
	MULTISOCIETAYN TINYINT(1) DEFAULT '0',
	ORDINABILEYN TINYINT(1) DEFAULT '0',
	DESCRIZIONEUNIVOCAYN TINYINT(1) DEFAULT '0',
	VALIDATORBEANNAME VARCHAR(100) NULL,
	CODICEEDITABILEYN TINYINT(1) DEFAULT '0',
	CACHEBLEYN TINYINT(1) DEFAULT '0',
	CATEGORIA VARCHAR(50) NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD UNIQUE UK_FRMK_ATTRIBUTE_TYPE_TIPO(TIPO);

# ----------  FRMK_ATTRIBUTE ----------
select "Create FRMK_ATTRIBUTE";
CREATE TABLE  FRMK_ATTRIBUTE (
	ID varchar(36) NOT NULL,
	TYPE varchar(50) NOT NULL,
	CODE varchar(50) NOT NULL,
	ORGANIZATION varchar(50) NOT NULL,
	LANGUAGE varchar(50) NOT NULL,
	ORDINAMENTO int(11) DEFAULT NULL,
	DESCRIPTION varchar(200) DEFAULT NULL,
	ATTRIBUTE1 varchar(1000) DEFAULT NULL,
	ATTRIBUTE2 varchar(1000) DEFAULT NULL,
	ATTRIBUTE3 varchar(500) DEFAULT NULL,
	ATTRIBUTE4 varchar(500) DEFAULT NULL,
	ATTRIBUTE5 varchar(250) DEFAULT NULL,
	ATTRIBUTE6 varchar(250) DEFAULT NULL,
	ATTRIBUTE7 varchar(50) DEFAULT NULL,
	ATTRIBUTE8 varchar(50) DEFAULT NULL,
	ATTRIBUTE9 varchar(50) DEFAULT NULL,
	ATTRIBUTE10 varchar(50) DEFAULT NULL,
	ACTIVEFLAG tinyint(1) DEFAULT '0',
	ACTIVEFLAGWK tinyint(1) DEFAULT '0',
	DELETEDATE datetime DEFAULT NULL,
	DELETEUSER varchar(50) DEFAULT NULL,
	PRIMARY KEY (ID)
);
ALTER TABLE FRMK_ATTRIBUTE ADD UNIQUE UK_FRMK_ATTRIBUTE_TCOL (TYPE,CODE,ORGANIZATION,LANGUAGE);

# ----------  FRMK_ATTRIBUTE_TYPE_ATTRIBUTE ---------- 
select "Create FRMK_ATTRIBUTE_TYPE_ATTRIBUTE";
CREATE TABLE  FRMK_ATTRIBUTE_TYPE_ATTRIBUTE (
  ID varchar(36) NOT NULL,
  CODE varchar(50) NOT NULL,
  VISIBILEYN tinyint(1) DEFAULT '0',
  TIPO varchar(50) DEFAULT NULL,
  TIPOATTRIBUTE varchar(50) DEFAULT NULL,
  OBBLIGATORIOYN tinyint(1) DEFAULT '0',
  RICERCAYN tinyint(1) DEFAULT '0',
  AUTOGENERATOYN tinyint(1) DEFAULT '0',
  AUTOGENBEANNAME varchar(50) DEFAULT NULL,
  POSIZIONEINLISTA int(10) unsigned DEFAULT NULL,
  ATTRIBUTETYPE_ID varchar(36) NOT NULL,
  PRECISIONINT int(11) DEFAULT NULL,
  SCALE int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);

# ----------  FRMK_CONFIG_METADATA ---------- 
SELECT "CREATE FRMK_CONFIG_METADATA";
CREATE TABLE FRMK_CONFIG_METADATA (
  CONFIGMETADATAID VARCHAR(36) NOT NULL,
  CODE VARCHAR(200) NOT NULL,
  APPLICATION VARCHAR(50) NOT NULL,
  SECTION VARCHAR(50) DEFAULT NULL,
  FIELDSET VARCHAR(50) DEFAULT NULL,
  POSITION NUMERIC(5,0) DEFAULT NULL,
  LABEL VARCHAR(50) DEFAULT NULL,
  HELPER VARCHAR(1000) DEFAULT NULL,
  TYPE VARCHAR(50) NOT NULL,
  TYPEDOMAIN VARCHAR(50) DEFAULT NULL,
  MULTIPLEYN TINYINT(1) DEFAULT '0',
  MAPYN TINYINT(1) DEFAULT '0',
  COMPANYYN TINYINT(1) DEFAULT '0',
  CLUSTERYN TINYINT(1) DEFAULT '0',
  SYSTEMYN TINYINT(1) DEFAULT '0',
  MANDATORYYN TINYINT(1) DEFAULT '0',
  CONFIGURABLEVALUESYN TINYINT(1) DEFAULT '1',
  MANDATORYCONFIGCODELEADER VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (CONFIGMETADATAID),
  UNIQUE KEY UK_FRMK_CONFIG_METADATA (APPLICATION,CODE)
);


#----------  FRMK_CONFIG	---------- 
SELECT "CREATE FRMK_CONFIG";
CREATE TABLE  FRMK_CONFIG (
  CONFIGID VARCHAR(36) NOT NULL,
  CODE VARCHAR(200) NOT NULL,
  POSITION INT(11) DEFAULT NULL,
  MAPKEY VARCHAR(200) DEFAULT NULL,
  COMPANY VARCHAR(50) NOT NULL,
  NODENAME VARCHAR(50) DEFAULT NULL,
  VALUE VARCHAR(2000) NOT NULL,
  CONFIGMETADATA_ID VARCHAR(36) NOT NULL,
  PRIMARY KEY (CONFIGID),
  KEY FRMK_CONFIG_CONFIGMETADATA (CONFIGMETADATA_ID)
);

ALTER TABLE FRMK_CONFIG ADD FOREIGN KEY (CONFIGMETADATA_ID) REFERENCES FRMK_CONFIG_METADATA(CONFIGMETADATAID);

# ---------- FRMK_COUNTER ---------- 
select "Create FRMK_COUNTER";
CREATE TABLE  FRMK_COUNTER (
  NAME varchar(100) NOT NULL,
  VALUE NUMERIC(19,0) NOT NULL,
  PRIMARY KEY (NAME)
);

# ---------- FRMK_EXCEPTION_LOG ---------- 
select "Create FRMK_EXCEPTION_LOG";
CREATE TABLE  FRMK_EXCEPTION_LOG (
  PROGRESSIVE NUMERIC(19,0) NOT NULL,
  CONTEXTNAME varchar(50) NOT NULL,
  DATEANDTIME datetime NOT NULL,
  MESSAGE varchar(500) DEFAULT NULL,
  APPLICATIONUSER varchar(100) DEFAULT NULL,
  STACKTRACE text DEFAULT NULL,
  ADDITIONALDATA text DEFAULT NULL,
  USERCONTEXTDATA text DEFAULT NULL,
  PRIMARY KEY (PROGRESSIVE)
);

# ---------- FRMK_INFO ----------
select "Create FRMK_INFO";
CREATE TABLE  FRMK_INFO (
  DESCRIPTION varchar(100) NOT NULL,
  VALUE varchar(50) NOT NULL,
  PRIMARY KEY (DESCRIPTION)
);

# ----------  FRMK_LISTPREF ---------- 
select "Create FRML_LISTPREF";
CREATE TABLE  FRMK_LISTPREF (
  ID varchar(36) NOT NULL,
  ACTIONNAME varchar(50) NOT NULL,
  USERNAME varchar(50) NOT NULL,
  PRIMARY KEY (ID)
);

# ----------  FRMK_LISTPREF_COL ---------- 
select "Create FRMK_LISTPREF_COL";
CREATE TABLE  FRMK_LISTPREF_COL (
  ID varchar(36) NOT NULL,
  COLUMNNAME varchar(50) NOT NULL,
  POSITION int(11) DEFAULT NULL,
  WIDTH int(11) DEFAULT NULL,
  VISIBLE tinyint(1) DEFAULT '0',
  LISTPREFERENCE_ID varchar(36) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK1LISTPREF_COL (LISTPREFERENCE_ID),
  CONSTRAINT FK_FRMK_LISTPREF_COL_LISTPREFERENCE_ID FOREIGN KEY (LISTPREFERENCE_ID) REFERENCES FRMK_LISTPREF (ID)
);

ALTER TABLE FRMK_LISTPREF_COL ADD FOREIGN KEY (LISTPREFERENCE_ID) REFERENCES FRMK_LISTPREF(ID);

# ----------  FRMK_LOCKGROUP ----------
select "Create FRMK_LOCKGROUP";
CREATE TABLE  FRMK_LOCKGROUP (
  ID varchar(36) NOT NULL,
  NUMLOCK decimal(19,0) DEFAULT NULL,
  LOCKTIME datetime DEFAULT NULL,
  CHECKTIME datetime DEFAULT NULL,
  LOCKUSER varchar(255) DEFAULT NULL,
  MACHINENAME varchar(255) DEFAULT NULL,
  SYSTEM tinyint(4) DEFAULT NULL,
  PRIMARY KEY (ID)
);

# ----------  FRMK_LOCKITEM ---------- 
select "Create FRMK_LOCKITEM";
CREATE TABLE  FRMK_LOCKITEM (
  ID varchar(36) NOT NULL,
  NAME varchar(50) DEFAULT NULL,
  GROUPID varchar(50) DEFAULT NULL,
  KEYID varchar(250) DEFAULT NULL,
  DESCRIPTION varchar(250) DEFAULT NULL,
  PRIMARY KEY (ID)
) ;

# ---------- 	FRMK_MESSAGE ---------- 
select "Create FRMK_MESSAGE";
CREATE TABLE  FRMK_MESSAGE (
  messageId varchar(36) NOT NULL,
  content varchar(1000) NOT NULL,
  expiration datetime NOT NULL,
  PRIMARY KEY (messageId)
) ;


INSERT INTO FRMK_INFO (VALUE,DESCRIPTION) VALUES ('03.00.00', 'FRAMEWORK-SQLSERVER-CREATE.SQL');	


select "INSERT DEFAULT VALUE ON FRMK_CONFIG_METADATA";
INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN)
VALUES ('1CA349A6-3F3E-444A-9D08-03ED17DBB595', 'FRMK001_MaxTimeToLockInMin', 'FRAMEWORK', 'LOCKMANAGER', 'MAX TIME TO LOCK (IN MIN)', NULL, NULL, NULL, 'INTEGER', NULL, 0, 0, 0, 0, 0);

INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('098751A3-2E96-4695-A287-4BAC7D19F9C5', 'FRMK001_MaxTimeToLockInMin', NULL, NULL, 'DEFAULT', NULL, '240', '1CA349A6-3F3E-444A-9D08-03ED17DBB595');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN)
VALUES ('22FFD69D-B945-4E16-8536-A0489F5E4E2F', 'FRMK002_TimeGuaranteedInMin', 'FRAMEWORK', 'LOCKMANAGER', 'TIME GUARANTEED FOR LOCK(IN MIN)', NULL, NULL, NULL, 'INTEGER', NULL, 0, 0, 0, 0, 0);

INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('7364B8B9-4CED-4DA3-B7F4-1AA2DB99F310', 'FRMK002_TimeGuaranteedInMin', NULL, NULL, 'DEFAULT', NULL, '2', '22FFD69D-B945-4E16-8536-A0489F5E4E2F');

		
UPDATE FRMK_INFO SET VALUE = '03.00.01' WHERE DESCRIPTION = 'FRAMEWORK-SQLSERVER-CREATE.SQL';

UPDATE FRMK_INFO SET DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL' WHERE DESCRIPTION = 'FRAMEWORK-SQLSERVER-CREATE.SQL';

UPDATE FRMK_INFO SET VALUE = '03.00.02' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN)
VALUES ('0F69F14F-382A-445C-B55B-02137CD1A6B5', 'FRMK003_Cluster', 'FRAMEWORK', 'CONFIG', 'CONFIG', NULL, NULL, NULL, 'STRING', NULL, 1, 0, 0, 0, 0);

INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('4910CB84-310A-4223-8CE1-9DDBB7FEDB69', 'FRMK003_Cluster', 1, NULL, 'DEFAULT', NULL, 'LocalNode', '0F69F14F-382A-445C-B55B-02137CD1A6B5');

UPDATE FRMK_INFO SET VALUE = '03.00.03' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('27a54d13-7f73-4c40-9089-d3529b578537','FRMK004_ApplicationLogFilePaths','FRAMEWORK','CONFIG','CONFIG',NULL,NULL,NULL,'STRING',NULL,1,0,0,0,0,1,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('ea51c07e-3a47-4e9e-b2b8-366b594a58a7','FRMK005_HostCall','FRAMEWORK','CONFIG','CONFIG',NULL,NULL,NULL,'STRING',NULL,1,1,0,0,0,0,1);

UPDATE FRMK_INFO SET VALUE = '03.00.04' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('0064269e-de5f-4341-af73-f01b88fd3379',	'FRMK006_LoginUrl','Framework',	'authentication','cas-client',NULL,'CAS login url','Secure URL whereat CAS offers its login service.','STRING',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('7e4fcff2-ae49-429b-9661-01e0e7744787','FRMK007_LoginFromRequest','Framework','authentication','cas-client',NULL,'Login from request','	Use request server name to compose login url','Boolean',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('2cad570a-6c59-4cd6-850d-65ebe397c6ae','FRMK008_CasValidateUrl','Framework','authentication','cas-client',NULL,'CAS validate url','Secure URL whereat CAS offers its CAS 2.0 validate service.','STRING',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('6dd7c92f-446e-4c3c-8dbb-c7ac812caeca','FRMK009_CasServiceUrl','Framework','authentication','cas-client',NULL,'CAS service url','Filtered service URL for use as service parameter to login and validate.','STRING',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4ee4a37f-a391-4253-a56f-906228ed2e14','FRMK010_Renew','Framework','authentication','cas-client',NULL,'Renew','True if renew parameter should be set on login and validate','Boolean',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('45dafcf4-6c30-45b7-9f9d-3fe5d2fd4ca3','FRMK011_ServerName','Framework','authentication','cas-client',NULL,'Server name','Name of server, for use in assembling service URL for use as service parameter to login and validate.','STRING',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9087e474-034a-43e4-baf0-7ec03037bfac','FRMK012_ServerNameFormRequest','Framework','authentication','cas-client',NULL,'Server name form request','Use request server name','Boolean',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('36947b22-df5b-4e59-baab-7e0bb5e8c8da','FRMK013_CasProxyCallbackUrl','Framework','authentication','cas-client',NULL,'Cas Proxy','Callback Secure URL whereto this filter should ask CAS to send Proxy Granting Tickets.','STRING',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('619b1f17-3ba0-4366-b942-0197c0939355','FRMK014_WrapRequest','Framework','authentication','cas-client',NULL,'Wrap request',NULL,'Boolean',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('e5a92ce2-7a08-4315-a43b-33d55195a22a','FRMK015_AuthorizedProxy','Framework','authentication','cas-client',NULL,'Authorized Proxy',NULL,'Boolean',NULL,1,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('be51270a-7a15-472b-8566-d5231d9b594e','FRMK016_AppplicationLogoutUrl','Framework','authentication','cas-client',NULL,'Application logout url',NULL,'STRING',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab41df511f','FRMK017_CasLogoutUrl','Framework','authentication','cas-client',NULL,'Cas logout url',NULL,'STRING',NULL,0,0,0,1,0,0,1);

UPDATE FRMK_INFO SET VALUE = '03.00.05' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

ALTER TABLE FRMK_CONFIG_METADATA ADD metadataVersion INT NOT NULL DEFAULT 1;
ALTER TABLE FRMK_CONFIG_METADATA ADD valuesVersion INT NOT NULL DEFAULT 1;


ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD  typeVersion INT NOT NULL DEFAULT 1;
ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD valuesVersion INT NOT NULL DEFAULT 1;
	

CREATE TABLE FRMK_JOB (
    name NVARCHAR(200) NOT NULL PRIMARY KEY,
    context NVARCHAR(200) NOT NULL,
    cronExpression NVARCHAR(200),
    recoveryYN INT,
    statefulYN INT,
    className NVARCHAR(255)
 );

 CREATE TABLE FRMK_JOB_CONTEXT (
name NVARCHAR(200) NOT NULL PRIMARY KEY,
url NVARCHAR(200)
);

CREATE TABLE FRMK_JOB_HISTORY (
NAME NVARCHAR(255) NOT NULL,
COUNTER BIGINT NOT NULL,
CONTEXT NVARCHAR(200),
NODENAME NVARCHAR(200),
DATE_START DATETIME,
DATE_END DATETIME,
DURATION BIGINT,
STATE NVARCHAR(200),
MESSAGE TEXT,
RESULT NVARCHAR(200),
PRIMARY KEY (NAME, COUNTER)
);

CREATE TABLE FRMK_JOB_RUNNING (
NAME NVARCHAR(255) NOT NULL,
COUNTER BIGINT NOT NULL,
CONTEXT NVARCHAR(200),
NODENAME NVARCHAR(200),
STATE NVARCHAR(200),
percentage DECIMAL (6,2),
PRIMARY KEY (NAME, COUNTER)
);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab41df5120','FRMK026_SchedulerWorkerNumber','SCHEDULER','scheduler','scheduler',NULL,'Maximun numebr of parallel running job',NULL,'INTEGER',NULL,0,0,0,1,0,0,1);

INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab41df5120','FRMK026_SchedulerWorkerNumber',null,null,'DEFAULT','LocalNode','2','9354b7c2-4a8e-4cd2-be21-0eab41df5120');

CREATE TABLE FRMK_JOB_RUNNING_SUPPORT (
  CAMPO1 INT PRIMARY KEY
);

INSERT INTO FRMK_JOB_RUNNING_SUPPORT VALUES (1);
 
UPDATE FRMK_INFO SET VALUE = '03.00.06' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';


UPDATE FRMK_CONFIG_METADATA SET APPLICATION = 'Framework' WHERE CODE = 'FRMK026_SchedulerWorkerNumber';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab41df400f','FRMK018_MailStyleProps','Framework','mail','style',NULL,NULL,'Contains the style properties for compose mail body. Example: dark: #589069, normal: #E2EBE4, internalTable: , nameApplication: Framework','STRING',NULL,0,1,0,0,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab41df401f','FRMK027_MailStyleImage','Framework','mail','style',NULL,NULL,'Contains the image properties for compose mail body. Example: logo: /mail/images/logo_email.jpg, left: /mail/images/footer_left.jpg, right: /mail/images/footer_right.jpg','STRING',NULL,0,1,0,0,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f40000', 'FRMK019_SmtpServerName', 'Framework', 'mail', '_genericConfiguration', NULL, NULL, 'Indicates the name of the smpt server ', 'String', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f40001', 'FRMK020_SmtpServerPort', 'Framework', 'mail', '_genericConfiguration', NULL, NULL, 'Indicates the port of the smpt server. Default value: 25 ', 'Integer', NULL, 0, 0, 0, 0, 0, 0, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f40002', 'FRMK021_SmtpServerUsername', 'Framework', 'mail', '_genericConfiguration', NULL, NULL, 'Indicates the usermame used for the connection to the smpt server.', N'String', NULL, 0, 0, 0, 0, 0, 0, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f40003', 'FRMK022_SmtpServerPassword', 'Framework', 'mail', '_genericConfiguration', NULL, NULL, 'Indicates the password used for the connection to the smpt server.', N'String', NULL, 0, 0, 0, 0, 0, 0, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f40004', 'FRMK023_SmtpServerProtocol', 'Framework', 'mail', '_genericConfiguration', NULL, NULL, 'Indicates the protocol used for the connection to the smpt server. Default is smtp', N'String', NULL, 0, 0, 0, 0, 0, 0, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f40005', 'FRMK024_SmtpServerMailProperties', 'Framework', 'mail', '_genericConfiguration', NULL, NULL, 'Indicates the additional information used for the connection to the smpt server. See http://connector.sourceforge.net/doc-files/Properties.html.', N'String', NULL, 0, 1, 0, 0, 0, 0, 1);

UPDATE FRMK_INFO SET VALUE = '03.00.07' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';	

UPDATE FRMK_CONFIG_METADATA SET APPLICATION = 'Framework' WHERE code = 'FRMK001_MaxTimeToLockInMin';
UPDATE FRMK_CONFIG_METADATA SET APPLICATION = 'Framework' WHERE code = 'FRMK002_TimeGuaranteedInMin';
UPDATE FRMK_CONFIG_METADATA SET APPLICATION = 'Framework' WHERE code = 'FRMK003_Cluster';
UPDATE FRMK_CONFIG_METADATA SET APPLICATION = 'Framework' WHERE code = 'FRMK004_ApplicationLogFilePaths';
UPDATE FRMK_CONFIG_METADATA SET APPLICATION = 'Framework' WHERE code = 'FRMK005_HostCall';
	

# ----------  FRMK_LABEL ---------- 
select "Create FRMK_LABEL";
CREATE TABLE FRMK_LABEL(
	application varchar(20) NOT NULL,
	organization varchar(20) NOT NULL,
	language varchar(20) NOT NULL,
	labelId varchar(50) NOT NULL,
	translation varchar(1000) character set utf8 NOT NULL ,
	technicalLabel tinyint NOT NULL,
	activeFlagWk tinyint NOT NULL,
	PRIMARY KEY (application, organization,language,labelId)
	);	

ALTER TABLE FRMK_ATTRIBUTE ADD UPDATEDATE DATETIME NULL;

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60000', 'FRMK028_EnableSysAttImportXmlButton', 'Framework', 'Config', NULL, NULL, NULL, 'Enable or disable import xml button visualization from sys_attribute type list section', 'Boolean', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60001', 'FRMK029_EnableSysAttExportXmlButton', 'Framework', 'Config', NULL, NULL, NULL, 'Enable or disable export xml button visualization from sys_attribute type list section', 'Boolean', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60002', 'FRMK030_EnableSysAttGenerateScriptsButton', 'Framework', 'Config', NULL, NULL, NULL, 'Enable or disable generete scripts button visualization from sys_attribute type list section', 'Boolean', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60003', 'FRMK031_EnableSysConfigGenerateScriptsButton', 'Framework', 'Config', NULL, NULL, NULL, 'Enable or disable generete scripts button visualization from sys_config metadata list section', 'Boolean', NULL, 0, 0, 0, 0, 0, 1, 1);

DELIMITER $$
CREATE TRIGGER setUpdateDateInsertTrigger
BEFORE INSERT ON FRMK_ATTRIBUTE
FOR EACH ROW BEGIN
		SET NEW.updateDate = CURRENT_TIMESTAMP();
END;$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER setUpdateDateUpdateTrigger
BEFORE UPDATE ON FRMK_ATTRIBUTE
FOR EACH ROW BEGIN
		SET NEW.updateDate = CURRENT_TIMESTAMP();
END;$$
DELIMITER ;

UPDATE FRMK_INFO SET VALUE = '03.00.08' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60004', 'FRMK032_SchedulerContextUrl', 'Framework', 'Config', NULL, NULL, NULL, 'Context url of the application that calls a job from Scheduler', 'String', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60005', 'FRMK033_SchedulerUsername', 'Framework', 'Config', NULL, NULL, NULL, 'Username to log on scheduler application', 'String', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60006', 'FRMK034_SchedulerPassword', 'Framework', 'Config', NULL, NULL, NULL, 'Password to log on scheduler application', 'String', NULL, 0, 0, 0, 0, 0, 1, 1);

ALTER TABLE FRMK_JOB_RUNNING ADD creationDate DATETIME NULL;
ALTER TABLE FRMK_JOB_RUNNING ADD startDate DATETIME NULL;
ALTER TABLE FRMK_JOB_RUNNING ADD endDate DATETIME NULL;

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60007', 'FRMK035_CasAskPassword', 'Framework', 'authentication', 'cas-client', NULL, NULL, 'Set to true for request password of user to cas server', 'Boolean', NULL, 0, 0, 0, 0, 0, 1, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60008', 'FRMK036_LicensePublicKeyFile', 'Framework', 'license', 'license-filter', NULL, NULL, 'Path to public.key file. Es: ${catalina.home}/quixlicense/public.key', 'String', NULL, 0, 0, 0, 1, 0, 0, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60009', 'FRMK037_LicensePublicKeyName', 'Framework', 'license', 'license-filter', NULL, NULL, 'Reference to public on classpath. Es: it/quix/project/public.key or public.key', 'String', NULL, 0, 0, 0, 0, 0, 0, 1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('4b7f1234-0035-47ed-af67-f234f9f60010', 'FRMK038_LicenseFile', 'Framework', 'license', 'license-filter', NULL, NULL, 'Path where license file is sored. Es: ${catalina.home}/quxlicense/quix.license', 'String', NULL, 0, 0, 0, 1, 0, 0, 1);

UPDATE FRMK_INFO SET VALUE = '03.00.09' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

ALTER TABLE FRMK_JOB_HISTORY ADD threadName VARCHAR(200);

ALTER TABLE FRMK_JOB_RUNNING ADD log TEXT;
ALTER TABLE FRMK_JOB_RUNNING ADD result VARCHAR(5);
ALTER TABLE FRMK_JOB_RUNNING ADD threadName VARCHAR(200);

ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD genere VARCHAR(50) NULL;
ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD usatoDa VARCHAR(500) NULL;
ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD fromVersion VARCHAR(250) NULL;

ALTER TABLE FRMK_ATTRIBUTE_TYPE_ATTRIBUTE ADD defaultValue VARCHAR(250) NULL;

ALTER TABLE FRMK_CONFIG_METADATA ADD kind VARCHAR(50) NULL;
ALTER TABLE FRMK_CONFIG_METADATA ADD fromVersion VARCHAR(250) NULL;
ALTER TABLE FRMK_CONFIG_METADATA ADD defaultValue VARCHAR(250) NULL;

UPDATE FRMK_INFO SET VALUE = '03.00.10' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-1eab41df5120','FRMK039_QDataDirectory','Framework','Custom','QData',NULL,'Qdata','Path of QData direcory. Es: c:/temp/Qdata','String',NULL,0,0,0,1,0,1,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-1eab41df5121','FRMK040_PumaProperties','Framework','Custom','QData',NULL,'Qdata','Propeties for PUMa. See puma.propetries file.','String',NULL,0,1,0,0,0,0,1);

ALTER TABLE FRMK_LABEL MODIFY COLUMN labelId NVARCHAR(250) NOT NULL;

UPDATE FRMK_INFO SET VALUE = '03.00.12' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

ALTER TABLE FRMK_JOB_RUNNING ADD stopped TINYINT(1) DEFAULT '0';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-1eab41df5001','FRMK041_DefaultCharactedEncoding','Framework','Config',NULL,NULL,'Character Encoding','The default character encoding to set for requests that pass through this filter.','String',NULL,0,0,0,0,0,1,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-1eab41df5002','FRMK042_IgnoreClientEncoding','Framework','Config',NULL,NULL,'Ignore client encoding','Indicates if a character encoding specified by the client must be ignored or not.','Boolean',NULL,0,0,0,0,0,1,1);

UPDATE FRMK_INFO SET VALUE = '03.00.13' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-1eab41df5003','FRMK043_ForceEncodingOnResponse','Framework','Config',NULL,NULL,'Force client encoding on response object','Indicates if a character encoding specified is set on response object or not.','Boolean',NULL,0,0,0,0,0,1,1);

CREATE TABLE FRMK_JOBNOTIFICATION (
	id VARCHAR(36) NOT NULL,
	execOrder INT(11) NOT NULL,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	datasource VARCHAR(100) NOT NULL,
	querySql TEXT NOT NULL,
	postQuerySql TEXT NULL,
	querySqlAsRSYN VARCHAR(1) NOT NULL,
	notifyYN VARCHAR(1) NOT NULL,
	notifyFromRSYN VARCHAR(1) NOT NULL,
	notifyTo VARCHAR(100) NULL,
	notifyCc VARCHAR(100) NULL,
	notifyBcc VARCHAR(100) NULL,
	notifySubject VARCHAR(100) NULL,
	notifyReplyTo VARCHAR(100) NULL,
	templateFtl TEXT NULL,
	enableYN VARCHAR(1) NOT NULL,
	lastExecutionDate datetime NULL,
	updateUser VARCHAR(50) NULL,
	updateDate datetime NULL,
	primary key (id)
);

UPDATE FRMK_INFO SET VALUE = '03.00.14' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-1eab41df5004','FRMK044_MailDefaultEncoding','Framework','Mail','_genericConfiguration',NULL,'Encoding','Set the default encoding used for send email. If not set, UTF-8 will be used','String',NULL,0,0,0,0,0,0,1);

CREATE TABLE FRMK_MAIL (
	mailId VARCHAR(36) NOT NULL,
	mailfrom VARCHAR(200),
	replyTo VARCHAR(200),
	mailto TEXT,
	cc TEXT,
	bcc TEXT,
	subject VARCHAR(300),
	templateName VARCHAR(100),
	body TEXT,
	templateNameTextPlain VARCHAR(100),
	bodyTextPlain TEXT,
	templateVars TEXT,
	embeddedimg TEXT,
	attachmentFiles TEXT,
	smtpHost VARCHAR(200),
	port INT,
	username VARCHAR(200),
	password VARCHAR(200),
	protocol VARCHAR(10),
	props TEXT,
	variables TEXT,
	sendDatetime DATETIME,
	sendResult VARCHAR(50),
	retryNr INT,
	errorMsg TEXT,
	defaultEncoding VARCHAR(20),
	lastRetryDatetime DATETIME,
	primary key (mailId)
);


UPDATE FRMK_INFO SET VALUE = '03.01.00' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

CREATE TABLE FRMK_EVENTDISPATCHER_REGISTER (
	component 		varchar(50) NOT NULL,
	context 		varchar(50) NOT NULL,
	node 			varchar(50) NOT NULL,
	beanId 			varchar(50) NOT NULL,
	registerDate 	datetime NOT NULL,
	commandList 	varchar(2000) NOT NULL,
	primary key (component, context, node)
);

CREATE TABLE FRMK_EVENTDISPATCHER_EVENT (
	component 			varchar(50) NOT NULL,
	context 			varchar(50) NOT NULL,
	node 				varchar(50) NOT NULL,
    progressiveNumber 	int NOT NULL,
	insertDate 			datetime NOT NULL,
	command 			varchar(50) NOT NULL,
	extraData 			text NULL,
    user                varchar(50) NULL,
    persistenceYN       tinyint NOT NULL,
    retryNr             int NOT NULL,
    maxRetryNr          int NOT NULL,
	primary key (component, context, node, progressiveNumber)
);

CREATE TABLE FRMK_EVENTDISPATCHER_HISTORY (
	component 			varchar(50) NOT NULL,
	context 			varchar(50) NOT NULL,
	node 				varchar(50) NOT NULL,
    progressiveNumber 	int NOT NULL,
	insertDate 			datetime NOT NULL,
	command 			varchar(50) NOT NULL,
	extraData 			text NULL,
    template         	text NULL,
	executeDate 		datetime NOT NULL,
    user                varchar(50) NULL,
    persistenceYN       tinyint NOT NULL,
    retryNr             int NOT NULL,
    maxRetryNr          int NOT NULL,
    successYN           varchar(10) NOT NULL,
	primary key (component, context, node, progressiveNumber)
);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('26b00240-865d-11e6-873b-0050568a0098','FRMK045_EventDispatcherMaxRetryNr','Framework','EventDispatcher','_genericConfiguration',NULL,'MaxRetryNr','Set max number of retries for event dispatcher to execute','Integer',NULL,0,0,0,0,0,0,1);

UPDATE FRMK_INFO SET VALUE = '03.01.01' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000003','FRMK046_HttpClientPoolSize','Framework','Notification','Android',NULL,'Size', 'Size of connection manager pool used by HTTP Client ','INTEGER',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000003','FRMK046_HttpClientPoolSize',null,null,'DEFAULT',null,'300','9354b7c2-4a8e-4cd2-be21-0eab00000003');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000004','FRMK47_GcmAuthorizationKey','Framework','Notification','Android',NULL,'Key', 'Authorization Key for Google Cloud Messaging','String',NULL,0,1,0,0,0,1,1);
-- INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
-- VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000004','FRMK47_GcmAuthorizationKey',null,null,'DEFAULT',null,'300','9354b7c2-4a8e-4cd2-be21-0eab00000004');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000001','FRMK048_GcmServiceUrl','Framework','Notification','Android',NULL,'Url', 'Google Cloud Messaging base url. Default value: https://gcm-http.googleapis.com/gcm/send','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000001','FRMK048_GcmServiceUrl',null,null,'DEFAULT',null,'https://gcm-http.googleapis.com/gcm/send','9354b7c2-4a8e-4cd2-be21-0eab00000001');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('26b00240-865d-11e6-873b-0050568a1234','FRMK049_NotificationHistoryMaxMessages','Framework','Notification','General',NULL,'Max message','Number max of message stored on database for user and device','Integer',NULL,0,0,0,0,0,0,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('26b00240-865d-11e6-873b-0050568a1234','FRMK049_NotificationHistoryMaxMessages',null,null,'DEFAULT',null,'15','26b00240-865d-11e6-873b-0050568a1234');

INSERT INTO FRMK_CONFIG_METADATA(configMetadataId, code, application, section, fieldset, position, label, helper, type, typeDomain, multipleYN, mapYN, companyYN, clusterYN, systemYN, mandatoryYN, configurableValuesYN, mandatoryConfigCodeLeader)
VALUES ('26b00240-865d-11e6-873b-0050568a0099', 'FRMK050_FrameworkTheme', 'Framework', 'Style', 'Theme', NULL, NULL, 'Set the style of the framework theme', 'String', NULL, 0, 0, 0, 0, 0, 0, 1, NULL);


INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000005','FRMK051_NotificationIcon','Framework','Notification','General',NULL,'Icon','Icon (image on jpeg format) to dispath to device to be notificated','String',NULL,0,1,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000005','FRMK051_NotificationIcon',null,'DEFAULT_ICON','DEFAULT',null,'', '9354b7c2-4a8e-4cd2-be21-0eab00000005');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000006','FRMK052_NotificationMaxRetryNumber','Framework','Notification','General',NULL,'Max','Number max of retry to send notification. Default 3','Integer',NULL,0,0,0,0,0,0,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000006','FRMK052_NotificationMaxRetryNumber',null,null,'DEFAULT',null,'3','9354b7c2-4a8e-4cd2-be21-0eab00000006');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000007','FRMK53_ApnsCertificatePath','Framework','Notification','IOS',NULL,'Path', 'Full path name of certificate for connect to APNS system','String',NULL,0,1,0,0,0,1,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000008','FRMK54_ApnsCertificatePassword','Framework','Notification','IOS',NULL,'Path', 'Password of certificate for connect to APNS system','String',NULL,0,0,0,0,0,1,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000009','FRMK55_ApnsProductionMode','Framework','Notification','IOS',NULL,'Path', 'Mode for connect to APNS system. True = Production Mode, False = Test Mode','String',NULL,0,0,0,0,0,1,1);


CREATE TABLE FRMK_NOTIFICATION(
	ID VARCHAR(36) NOT NULL,
	USERID varchar(50) NOT NULL,
	CHANNELTYPE varchar(50) NOT NULL,
	CHANNELID varchar(350) NOT NULL,
	COLLAPSEKEY varchar(50) NULL,
	CONTENTAVAILABLE tinyint NULL,
	TITLE varchar(100) NULL,
	BODY varchar(500) NULL,
	PAYLOAD text NULL,
	ICON varchar(50) NULL,
	INSERTDATE DATETIME NULL,
	SCHEDULEDATE TIMESTAMP NULL,
	SENDDATE DATETIME NULL,
	RETRYNR int NULL,
	LASTRETRYDATE DATETIME NULL,
	RESULT varchar(50) NULL,
	RESULTMESSAGE text NULL,
	primary key (ID)
);

CREATE TABLE FRMK_NOTIFICATION_HISTORY(
	ID VARCHAR(36) NOT NULL,
	USERID varchar(50) NOT NULL,
	CHANNELTYPE varchar(50) NOT NULL,
	CHANNELID varchar(350) NOT NULL,
	COLLAPSEKEY varchar(50) NULL,
	CONTENTAVAILABLE smallint NULL,
	TITLE varchar(100) NULL,
	BODY varchar(500) NULL,
	PAYLOAD text NULL,
	ICON varchar(50) NULL,
	SENDDATE DATETIME NULL,
	READYN tinyint NULL,
	VISIBLEYN tinyint NULL,
	NOTIFICATIONID varchar(36) NULL,
	EXTERNALSTATICID varchar(50) NULL,
	primary key (ID)
);

CREATE TABLE FRMK_NOTIFICATION_REGISTRY(
	ID varchar(36) NOT NULL,
	USERID varchar(50) NOT NULL,
	CHANNELTYPE varchar(50) NOT NULL,
	CHANNELID varchar(350) NOT NULL,
	CHANNELTOKEN varchar(500) NOT NULL,
	APPNAME varchar(50) NOT NULL,
	CREATIONDATE DATETIME NULL,
	ACCESSCOUNTER int NULL,
	LASTACCESSDATE DATETIME NULL,
	TIMEZONE varchar(200) NULL,
	primary key (ID)
);

CREATE INDEX IX_FRMK_NOTIFICATION_REGISTRY_1 ON FRMK_NOTIFICATION_REGISTRY(USERID, CHANNELTYPE, CHANNELID);
CREATE INDEX IX_FRMK_NOTIFICATION_REGISTRY_2 ON FRMK_NOTIFICATION_REGISTRY(CHANNELTYPE, CHANNELID);

CREATE INDEX IX_FRMK_NOTIFICATION_HISTORY_1 ON FRMK_NOTIFICATION_HISTORY(USERID, CHANNELTYPE, CHANNELID);
CREATE INDEX IX_FRMK_NOTIFICATION_HISTORY_2 ON FRMK_NOTIFICATION_HISTORY(CHANNELTYPE, CHANNELID);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000010','FRMK56_NotificationBeginHour','Framework','Notification','General',NULL,'Path', 'Hour to begin to notify user','Integer',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000010','FRMK56_NotificationBeginHour',null,null,'DEFAULT', null,'8','9354b7c2-4a8e-4cd2-be21-0eab00000010');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000011','FRMK57_NotificationEndHour','Framework','Notification','General',NULL,'Path', 'Hour to begin to notify user','Integer',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000011','FRMK57_NotificationEndHour',null,null,'DEFAULT', null,'22','9354b7c2-4a8e-4cd2-be21-0eab00000011');

ALTER TABLE FRMK_NOTIFICATION_REGISTRY ADD COLUMN language VARCHAR(2);
ALTER TABLE FRMK_EVENTDISPATCHER_EVENT ADD COLUMN userId VARCHAR(50);
ALTER TABLE FRMK_EVENTDISPATCHER_EVENT DROP COLUMN user;
ALTER TABLE FRMK_EVENTDISPATCHER_HISTORY ADD userId VARCHAR(50);
ALTER TABLE FRMK_EVENTDISPATCHER_HISTORY DROP COLUMN user;

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000012','FRMK58_ForceAllMailTo','Framework','mail', '_genericConfiguration',NULL,'Email', 'Force all email to be sent to this customer','String',NULL,1,0,0,0,0,0,1);

DELETE FROM FRMK_CONFIG WHERE CODE = 'FRMK051_NotificationIcon';
DELETE FROM FRMK_CONFIG_METADATA WHERE CODE = 'FRMK051_NotificationIcon';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000005','FRMK051_NotificationIconBasePath','Framework','Notification','General',NULL,'folder','Base folder of Icon (image on .png format) to show in notification list','String',NULL,0,0,0,0,0,1,1);

UPDATE FRMK_CONFIG_METADATA SET MAPYN = 0 WHERE CODE IN ('FRMK56_NotificationBeginHour', 'FRMK57_NotificationEndHour');

UPDATE FRMK_INFO SET VALUE = '03.01.02' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

DROP INDEX IX_FRMK_NOTIFICATION_REGISTRY_1 ON FRMK_NOTIFICATION_REGISTRY;
CREATE INDEX IX_FRMK_NOTIFICATION_REGISTRY_1 ON FRMK_NOTIFICATION_REGISTRY(USERID , CHANNELTYPE);
CREATE INDEX IX_FRMK_NOTIFICATION_REGISTRY_3 ON FRMK_NOTIFICATION_REGISTRY(CHANNELID);

ALTER TABLE FRMK_MAIL MODIFY COLUMN mailto VARCHAR(1000);
ALTER TABLE FRMK_MAIL MODIFY COLUMN cc VARCHAR(1000);
ALTER TABLE FRMK_MAIL MODIFY COLUMN bcc VARCHAR(1000);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000013','FRMK59_NotificationMaxChunkSize','Framework','Notification','General',NULL,'Max chunk size','Notification with same content and channel will be grouped in chunk with max size as set. Default 1000','Integer',NULL,0,0,0,0,0,0,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000013','FRMK59_NotificationMaxChunkSize',null,null,'DEFAULT',null,'1000','9354b7c2-4a8e-4cd2-be21-0eab00000013');

UPDATE FRMK_INFO SET VALUE = '03.01.03' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

ALTER TABLE FRMK_NOTIFICATION_REGISTRY ADD COLUMN APPVERSION varchar(100) not null default 0;

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('ddec3b89-b222-11e6-9b5d-00fffe2441bf','FRMK060_SubscribeMailFrom','Framework','Login','Subscribe',NULL,'Subscribe mail from address','Email address of from field for subscribe mail','String',NULL,0,0,0,0,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('59daf64e-b223-11e6-9b5d-00fffe2441bf','FRMK061_SubscribeMailSubject','Framework','Login','Subscribe',NULL,'Subscribe mail subject','Subject of subscribe mail','String',NULL,0,0,0,0,0,0,1);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('5d423971-b223-11e6-9b5d-00fffe2441bf','FRMK062_SubscribeMailTemplateName','Framework','Login','Subscribe',NULL,'Subscribe mail template name','Template of subscribe mail','String',NULL,0,0,0,0,0,0,1);

DROP INDEX IX_FRMK_NOTIFICATION_HISTORY_1 ON FRMK_NOTIFICATION_HISTORY;
CREATE INDEX IX_FRMK_NOTIFICATION_HISTORY_1 ON FRMK_NOTIFICATION_HISTORY(USERID, CHANNELTYPE, CHANNELID);

UPDATE FRMK_INFO SET VALUE = '03.01.04' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

ALTER TABLE FRMK_MAIL ADD COLUMN priority INT;
ALTER TABLE FRMK_MAIL ADD COLUMN read_receipt VARCHAR(200);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000014','FRMK60_MailReadReceipt','Framework','mail','General',NULL,'Mail Read Receipt','Email for read report . Default blank','String',NULL,0,0,0,0,0,0,1);

UPDATE FRMK_INFO SET VALUE = '03.01.05' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

CREATE INDEX IX_FRMK_NOT_REG_3b ON FRMK_NOTIFICATION_REGISTRY (CHANNELTYPE, CHANNELTOKEN);

UPDATE FRMK_INFO SET VALUE = '03.01.06' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';

CREATE INDEX IX_FRMK_NOTIFICATION_HISTORY_4 ON FRMK_NOTIFICATION_HISTORY (NOTIFICATIONID);

UPDATE FRMK_INFO SET VALUE = '03.01.07' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';



-- VERSIONE 3.2.0
CREATE TABLE FRMK_URL_TOKEN (
	TOKEN VARCHAR(100) NOT NULL PRIMARY KEY,
	URL VARCHAR(1000),
	CREATEDATE DATETIME,
	CREATEUSER VARCHAR(50),
	VALIDITYDATE DATETIME,
	ONETIMETOKEN INT
);

CREATE TABLE FRMK_NOT_DEFAULT_PREFERENCE (
    id varchar(36) NOT NULL,
    notificationType varchar(50),
    channel varchar(50),
    groupId varchar(50),
    notificationStartTime datetime,
    notificationEndTime datetime,
    enabled tinyint,
    PRIMARY KEY (id)
);

CREATE TABLE FRMK_NOT_USER_PREFERENCE (
    id varchar(36) NOT NULL,
    userId varchar(50),
    notificationType varchar(50),
    channel varchar(50),
    channelId varchar(250),
    notificationStartTime datetime,
    notificationEndTime datetime,
    enabled tinyint,
    PRIMARY KEY (id)
);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000015','FRMK061_QBotHttpClientPoolSize','Framework','Notification','QBot',NULL,'Size', 'Size of connection manager pool used by HTTP Client to connect to QBot','INTEGER',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000015','FRMK061_QBotHttpClientPoolSize',null,null,'DEFAULT',null,'10','9354b7c2-4a8e-4cd2-be21-0eab00000015');


INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000016','FRMK062_QBotServiceUrl','Framework','Notification','QBot',NULL,'Url', 'QBot notification base url. ','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000016','FRMK062_QBotServiceUrl',null,null,'DEFAULT',null,'http://127.0.0.1/qbot/notification','9354b7c2-4a8e-4cd2-be21-0eab00000016');

CREATE TABLE FRMK_NOTIFICATION_TO_SEND (
	id varchar(50) NOT NULL,
	title varchar(1000) NULL,
	body varchar(4000) NULL,
	pushTitle varchar(100) NULL,
	pushBody varchar(500) NULL,
	payload text NULL,
	category varchar(50) NULL,
	externalId varchar(50) NULL,
	doNotSendMultipleNotification tinyint,
	userId varchar(50) NOT NULL,
	PRIMARY KEY (id)
);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000017','FRMK062_MailReplayTo','Framework','_genericConfiguration','mail',NULL,'Email', 'Replay to email ','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000017','FRMK062_MailReplayTo',null,null,'DEFAULT',null,'no-reply@quix.it','9354b7c2-4a8e-4cd2-be21-0eab00000017');


INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000018','FRMK064_SmsSurferPassword','Framework','Notification','SmsSurfer',NULL,'Password', 'Sms surfer password ','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000018','FRMK064_SmsSurferPassword',null,null,'DEFAULT',null,'','9354b7c2-4a8e-4cd2-be21-0eab00000018');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000019','FRMK065_SmsSurferOriginator','Framework','Notification','SmsSurfer',NULL,'Originator', 'Sms surfer originator. ','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000019','FRMK065_SmsSurferOriginator',null,null,'DEFAULT',null,'','9354b7c2-4a8e-4cd2-be21-0eab00000019');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000020','FRMK066_SmsSurferSmsType','Framework','Notification','SmsSurfer',NULL,'Type', 'Sms surfer Sms type. ','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000020','FRMK066_SmsSurferSmsType',null,null,'DEFAULT',null,'','9354b7c2-4a8e-4cd2-be21-0eab00000020');

ALTER TABLE FRMK_NOTIFICATION_HISTORY MODIFY COLUMN TITLE VARCHAR(1000);
ALTER TABLE FRMK_NOTIFICATION_HISTORY MODIFY COLUMN BODY VARCHAR(4000);

ALTER TABLE FRMK_NOTIFICATION MODIFY COLUMN TITLE VARCHAR(1000);
ALTER TABLE FRMK_NOTIFICATION MODIFY COLUMN BODY VARCHAR(4000);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000021','FRMK067_DefaultFromMail','Framework','_genericConfiguration','mail',NULL,'Email', 'Default from email ','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000021','FRMK067_DefaultFromMail',null,null,'DEFAULT',null,'framework@quix.it','9354b7c2-4a8e-4cd2-be21-0eab00000021');

CREATE TABLE FRMK_AUTHCODE (
    id varchar(50) NOT NULL,
    userId varchar(50) NOT NULL,
    expireDate datetime,
    oneTime bit,
    source varchar(50),
    userSerialized text
);
ALTER TABLE FRMK_AUTHCODE ADD CONSTRAINT PK_AUTHCODE_ID PRIMARY KEY (id);

ALTER TABLE FRMK_ATTRIBUTE_TYPE ADD COLUMN cancellazioneFisicaYN TINYINT(1) DEFAULT 0;

CREATE TABLE FRMK_USERPROFILE (
	userProfileId varchar(36) NOT NULL,
	userId varchar(50) NOT NULL,
	attribute varchar(150) NOT NULL,
	ordernr int NOT NULL,
	value varchar(250) NULL,
    PRIMARY KEY (userProfileId)
);

CREATE TABLE FRMK_TEMPLATE (
	templateId varchar(36) NOT NULL,
	application varchar(20) NOT NULL,
	organization varchar(20) NOT NULL,
	language varchar(20) NOT NULL,
	name varchar(250) NOT NULL,
	ftl TEXT NOT NULL,
	creationDate datetime NOT NULL,
	creationUser varchar(50) NOT NULL,
	updateDate datetime NOT NULL,
	updateUser varchar(50) NOT NULL,
	PRIMARY KEY (templateId)
);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000022','FRMK068_AuthcodeVersionDefault','Framework','authentication','authcode',NULL, 'Email', 'Default version of authcode','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000022','FRMK068_AuthcodeVersionDefault',null,null,'DEFAULT',null,'1','9354b7c2-4a8e-4cd2-be21-0eab00000022');

CREATE TABLE FRMK_NOTIFICATION_ACTION (
  id         VARCHAR(36) NOT NULL,
  category   VARCHAR(50),
  name       VARCHAR(50),
  icon       VARCHAR(50),
  label_key  VARCHAR(50),
  sorting      INT,
  base_url   VARCHAR(500),
  PRIMARY KEY (id)
);

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000025','FRMK068_AzureBaseUrl','Framework','Notification','Azure',NULL,'Size', 'Azure base url','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000025','FRMK068_AzureBaseUrl',null,null,'DEFAULT',null,'sb://progettoapp.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=','9354b7c2-4a8e-4cd2-be21-0eab00000025');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000026','FRMK069_AzureHttpClientPoolSize','Framework','Notification','Azure',NULL,'Size', 'Size of connection manager pool used by HTTP Client to connect to Azure','INTEGER',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000026','FRMK069_AzureHttpClientPoolSize',null,null,'DEFAULT',null,'10','9354b7c2-4a8e-4cd2-be21-0eab00000026');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000027','FRMK070_AzureAccessKey','Framework','Notification','Azure',NULL,'Size', 'Access Key to connect to Azure','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000027','FRMK070_AzureAccessKey',null,null,'DEFAULT',null,'','9354b7c2-4a8e-4cd2-be21-0eab00000027');

UPDATE FRMK_CONFIG_METADATA
SET CODE = 'FRMK071_AuthcodeVersionDefault'
WHERE CODE = 'FRMK068_AuthcodeVersionDefault';

UPDATE FRMK_CONFIG
SET CODE = 'FRMK071_AuthcodeVersionDefault'
WHERE CODE = 'FRMK068_AuthcodeVersionDefault';

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000028','FRMK072_QBotNotificationSenderPlaceholderRoot','Framework','Notification','QBot',NULL, 'Root object', 'Root object for placeholder map in payload. Leave blank if placeholder map is the payload itself','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000028','FRMK072_QBotNotificationSenderPlaceholderRoot',null,null,'DEFAULT',null,'','9354b7c2-4a8e-4cd2-be21-0eab00000028');

INSERT INTO FRMK_CONFIG_METADATA (CONFIGMETADATAID, CODE, APPLICATION, SECTION, FIELDSET, POSITION, LABEL, HELPER, TYPE, TYPEDOMAIN, MULTIPLEYN, MAPYN, COMPANYYN, CLUSTERYN, SYSTEMYN, MANDATORYYN, CONFIGURABLEVALUESYN)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000029','FRMK073_AzureHubPath','Framework','Notification','Azure',NULL,'Path', 'Azure Hub Path','String',NULL,0,0,0,0,0,1,1);
INSERT INTO FRMK_CONFIG (CONFIGID, CODE, POSITION, MAPKEY, COMPANY, NODENAME, VALUE, CONFIGMETADATA_ID)
VALUES ('9354b7c2-4a8e-4cd2-be21-0eab00000029','FRMK073_AzureHubPath',null,null,'DEFAULT',null,'','9354b7c2-4a8e-4cd2-be21-0eab00000029');

UPDATE FRMK_INFO SET VALUE = '03.02.00' WHERE DESCRIPTION = 'FRAMEWORK-MYSQL-CREATE.SQL';
